global using CloudinaryDotNet;
global using CloudinaryDotNet.Actions;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Identity.UI.Services;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Options;
global using SendGrid;
global using SendGrid.Helpers.Mail;
global using Slice.Utilities.Helpers;
